Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get "quick_log/create"
      get "emotional_episodes/index"
      get "emotional_episodes/create"
      get "emotional_episodes/show"
    end
  end
  get "prediction_feedbacks/index"
  get "prediction_feedbacks/show"
  get "prediction_feedbacks/new"
  get "prediction_feedbacks/create"
  get "prediction_feedbacks/edit"
  get "prediction_feedbacks/update"
  get "prediction_feedbacks/destroy"
  get "prediction_feedbacks/quick_feedback"
  get "analytics/dashboard"
  get "analytics/emotions"
  get "analytics/triggers"
  get "analytics/patterns"
  get "analytics/export"
  get "user_goals/index"
  get "user_goals/show"
  get "user_goals/new"
  get "user_goals/create"
  get "user_goals/edit"
  get "user_goals/update"
  get "user_goals/destroy"
  get "user_goals/complete"
  get "user_goals/pause"
  get "behavior_reactions/index"
  get "behavior_reactions/show"
  get "behavior_reactions/new"
  get "behavior_reactions/create"
  get "behavior_reactions/edit"
  get "behavior_reactions/update"
  get "behavior_reactions/destroy"
  get "physical_symptoms/index"
  get "physical_symptoms/show"
  get "physical_symptoms/new"
  get "physical_symptoms/create"
  get "physical_symptoms/edit"
  get "physical_symptoms/update"
  get "physical_symptoms/destroy"
  get "physical_symptoms/quick_add"
  get "emotional_episodes/index"
  get "emotional_episodes/show"
  get "emotional_episodes/new"
  get "emotional_episodes/create"
  get "emotional_episodes/edit"
  get "emotional_episodes/update"
  get "emotional_episodes/destroy"
  get "emotional_episodes/quick_log"
  get "emotional_episodes/create_quick"
  get "diary_entries/index"
  get "diary_entries/show"
  get "diary_entries/new"
  get "diary_entries/create"
  get "diary_entries/edit"
  get "diary_entries/update"
  get "diary_entries/destroy"
  get "contexts/index"
  get "contexts/show"
  get "contexts/new"
  get "contexts/create"
  get "contexts/edit"
  get "contexts/update"
  get "contexts/destroy"
  get "coping_strategies/index"
  get "coping_strategies/show"
  get "coping_strategies/new"
  get "coping_strategies/create"
  get "coping_strategies/edit"
  get "coping_strategies/update"
  get "coping_strategies/destroy"
  get "triggers/index"
  get "triggers/show"
  get "triggers/new"
  get "triggers/create"
  get "triggers/edit"
  get "triggers/update"
  get "triggers/destroy"
  get "emotions/index"
  get "emotions/show"
  get "emotions/new"
  get "emotions/create"
  get "emotions/edit"
  get "emotions/update"
  get "emotions/destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end
